spring:
  data:
    ##4.0.1
    cassandra:
      keyspace-name: demo
      contact-points: 47.118.51.155
      port: 9042
      username: cassandra
      password: cassandra
      local-datacenter: datacenter1
server:
  port: 58080
