
spring:
  data:
    cassandra:
      keyspace-name: jarvis_datastore
      #entity-base-packages:
      contact-points: 47.118.51.155
      port: 9042
      cluster-name: cassandra_cluster
      username: cassandra
      password: cassandra
      local-datacenter: datacenter1
server:
  port: 58080
